### ISSUE TITLE
[Bug] [App] Android v0.0.49 - Account page missing?

### ISSUE THREAD

**Issue by iC3James** [TekExplorer/featherdactyl.com#54] opened 2023-02-21 19:30 UTC
**Describe the bug**

Account page not loading on Android App V0.0.49

**To Reproduce**

Steps to reproduce the behaviour:
```
1. Open App
2. Click 3 Dots
3. Select Account
4. Blank:page.png
```
**Expected behaviour**

I would expect the account settings page to load?

**Screenshots**

https://youtube.com/shorts/HtZ4IaqFgFA - shoulda tiktok'd it to 12 minutes to process a 14 second video -.-

**App:**
```
 - Version: 0.0.49
 - Build Number: 422
```
**Smartphone:**
```
 - Device: Samsung S22
 - OS: Android 13/One UI 5.1
 - Version: Latest Samsung Release - 1/02/23 (I am not writing out the full build number jesus)
```

**Comment by TekExplorer** [comment] 2023-02-21 20:04
Thats not exactly reproducible. A blank white page means an unexpected exception occurred.
Grab the logs from the preferences dialog.

Additionally, i will need to know if you are using stock Pterodactyl or if you have modified it (ex. with addons)

**Comment by iC3James** [comment] 2023-02-21 20:16
Not going to lie. I must have been blind when I've been going to the preferences tab haven't ever noticed the Copy Logs/Upload Logs button...

Logs: https://haste.oaka.xyz/zeredofiha

My Panel: 100% Stock, 2 Custom Eggs 0 Addons.

**Comment by TekExplorer** [comment] 2023-02-21 20:32
Strange. The error is about a lack of a server id, which doesn't make sense as the account page doesn't exactly need it.
Does the error appear if you have entered at least one server at least once?

**Comment by iC3James** [comment] 2023-02-22 11:12
I went into one server, restarted the server and then opened the account page.

It is still blank and here is the logs (mine are set to verbose, is there a preference?):

https://haste.oaka.xyz/aruwuworin

**Comment by iC3James** [comment] 2023-02-22 11:14
I went into one server, restarted the server, and then opened the account page.

It is still blank, and here is the logs (mine are set to verbose, is there a preference?):

https://haste.oaka.xyz/aruwuworin

**Comment by TekExplorer** [comment] 2023-02-22 18:22
honestly? this is probably something i hit and fixed locally, with the amount that's changed internally since v49
wait till that eventually is published and either close this issue if its fixed or let me know that its still a problem

**Comment by TekExplorer** [comment] 2023-03-06 18:20
This should be fixed. Reopen if it's not.

**Closed by TekExplorer** 2023-03-06 18:20 UTC
Labels: bug
