### ISSUE TITLE
[Feature request] Disable text wrapping on console (Android or devices with smaller screen)

### ISSUE THREAD

**Issue by larpedd** [TekExplorer/featherdactyl.com#58] opened 2024-03-02 06:17 UTC
hi, i think the text wrapping in android is necessary. why? when luckperms is initalized they look like this on normal pterodactyl:
![image](https://github.com/TekExplorer/featherdactyl.com/assets/53142287/4d339c35-1151-4eb7-82fc-ad8874dd718a)

Meanwhile in android:
![image](https://github.com/TekExplorer/featherdactyl.com/assets/53142287/e0096e36-a124-4031-a00a-2ebbc092e9d2)

It remains readable, but it is irritating on ascii art console thing

**Comment by TekExplorer** [comment] 2024-06-17 15:59
I'm working on replacing the existing console with my own custom implementation so I have better control over how it comes out

**Comment by TekExplorer** [comment] 2024-06-17 16:01
That being said, duplicate of #19

**Closed as completed by TekExplorer** 2024-06-17 16:01 UTC
