### ISSUE TITLE
[Bug] Font looks weird in console

### ISSUE THREAD

**Issue by matthias-codes** [TekExplorer/featherdactyl.com#47] opened 2022-07-31 14:33 UTC
**Describe the bug**
The font in console is glitched.

**To Reproduce**
```
1. Open console on a server
2. See error
```
**Expected behavior**
The font should look normal and not like in the screenshots below

**Screenshots**
![D6DE1B99-2FBC-43B5-9806-34F9B0188C33](https://user-images.githubusercontent.com/92888450/182031065-dc18b434-6cf7-43a5-a8da-7a33a32e8293.png)
![2CFCC673-7DFD-4F8E-8CC1-AA38D0C0BD12](https://user-images.githubusercontent.com/92888450/182031069-c99d4728-8e1c-4a28-a927-2cb4274f0c10.png)

**App (please complete the following information):**
```
 - Version: 0.0.22
 - Build Number: 224
```
**Desktop (please complete the following information):**
```
 - OS: -
 - Version: -
```
**Smartphone (please complete the following information):**
```
 - Device: iPhone 11
 - OS: iOS 16
 - Version 16.0 (20A5312g)
```
**Additional context**
-

**Comment by YusufYaser** [comment] 2022-07-31 16:29
Duplicate of #24

**Comment by TekExplorer** [comment] 2022-07-31 18:51
Duplicate of #24 indeed

**Closed by TekExplorer** 2022-07-31 18:51 UTC
Labels: bug
