### ISSUE TITLE
[Bug] Back button disappears

### ISSUE THREAD

**Issue by GabrieleYT9768** [TekExplorer/featherdactyl.com#46] opened 2022-07-04 03:50 UTC
**Describe the bug**
When you are on the user settings page, on the top-left there is a button to go back to servers list. Whenever you click on the Preferences button **while** you were on the user settings page, the button to go back just disappears and you are stuck.

**To Reproduce**
```
1. Open the user settings page
2. Click on the preferences button
3. Close the preferences page
4. The button on top left disappeares
```
**Expected behavior**
There should be a back button on the top left of the screen to go back to servers list, but instead the pterodactyl logo is there.

**Screenshots**
A video of the problem: https://vimeo.com/726588488

**App (please complete the following information):**
```
 - Version: v0.0.22
 - Build Number: 224
```

**Smartphone (please complete the following information):**
```
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.0
 - Version 16.0
```
**Additional context**
I'm actually using iOS 16.0, which is in beta, but that shouldn't be the reason of a graphic problem.

**Comment by TekExplorer** [comment] 2022-07-04 03:52
Duplicate of #35

**Closed** 2022-11-05 05:51 UTC
Labels: bug
